apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.container.name}}"
  labels:
    name: "{{.Values.container.name}}"
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  containers:
  - name: {{.Values.container.name}}
    image: "{{.Values.image}}"
    ports:
    - containerPort: {{.Values.container.port}}
      protocol: TCP
    envFrom:
      - configMapRef:
          name: postgresql-cm
    volumeMounts:
    - name: postgresql-data
      mountPath: "/var/lib/postgresql/data"
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
      claimName: "{{.Values.pvc.name}}"
