apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.container.name}}"
  labels:
    name: "{{.Values.container.name}}"
spec:
  ports:
  - protocol: TCP
    port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
    name: postgres
  selector:
    name: "{{.Values.container.name}}"
